Stressng Plugin in own repo and integration of GitHub Actions
arcalot/arcaflow-plugin-stressng pull request #2
Opened 2022-10-07 17:38 UTC by jdowni000

## Changes introduced with this PR

Creating a new PR. This one has 3 commits that have separated the removal of other plugins, flake8 code cleanup, and github actions integration with carpenter. 

---
By contributing to this repository, I agree to the [contribution guidelines](https://github.com/arcalot/.github/blob/main/CONTRIBUTING.md).

2022-10-07 19:59 UTC, portante approved these changes

2022-10-10 07:26 UTC, sandrobonazzola commented on .github/workflows/carpenter.yaml
> +        uses: arcalot/arcaflow-plugin-stressng-builder@main
Does this action exist? I can't see it

2022-10-12 09:36 UTC, sandrobonazzola requested changes
please check the github action being used for building

2022-10-21 20:20 UTC, portante approved these changes

2022-10-24 07:04 UTC, sandrobonazzola approved these changes

2022-10-24 07:04 UTC, merged